[package]
name = "rollercoaster"
description = "A set of useful iterators"

version = "0.0.2"
edition = "2021"
license = "MIT"

repository = "https://github.com/Enitoni/rollercoaster"
authors = [
  "Enitoni <root@enitoni.dev>"
]
